services:
  neo4j:
    image: 'neo4j:latest'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
    ports:
      - '7687'
    networks:
      - neo4j-ai-nw
networks:
  neo4j-ai-nw:
    driver: bridge