server:
  port: 8084
spring:
  ai:
    ollama:
      baseUrl: http://localhost:11434/
      chat:
        model: 'gemma:2b'
      embedding:
        options:
          model: 'gemma:2b'
        model: 'gemma:2b'

springdoc:
  swagger-ui:
    path: /swagger-ui.html

pdf:
  path: classpath:medicaid-wa-faqs.pdf