server:
  port: 8084
spring:
  ai:
    postgresml:
      embedding:
        options:
          transformer: distilbert-base-uncased
          vectorType: PG_ARRAY
          metadataMode: EMBED
          kwargs:
            device: cpu
  datasource:
    url: jdbc:postgresql://localhost/vector_store
    username: postgres
    password: postgres

pdf:
  path: classpath:medicaid-wa-faqs.pdf